version: '3.8'

services:
  postgres:
    image: postgres
    container_name: react-universe-conf-2024
    environment:
      POSTGRES_USER: mike
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
